// src/components/Clock.svelte
<script lang="ts">
	import { onMount } from "svelte";

	// -- Members -- \\
	let date: string;
	let time: string;

	// -- Initialization -- \\
	onMount(async () => {
		update();
	});

	// -- Functions -- \\
	async function update() {
		const d = new Date();
		date = new Intl.DateTimeFormat("en-GB", {
			year: "numeric",
			month: "short",
			day: "numeric",
			weekday: "short",
		}).format(d);

		time = new Intl.DateTimeFormat("en-GB", {
			hour: "numeric",
			minute: "numeric",
		}).format(d);

		setTimeout(() => {
			update();
		}, 5000);
	}
</script>

<article>
	<h1 class="mb-2 text-6xl text-center">{time}</h1>
	<p class="text-center">{date}</p>
</article>

// src/components/Clock.vue
<template>
  <article class="flex flex-col items-center justify-center">
    <h1 class="text-7xl text-center">
      {{ time }}
    </h1>
    <h3 class="text-2xl text-center">
      {{ date }}
    </h3>
  </article>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

export default defineComponent({
  setup() {
    const date = ref()
    const time = ref()

    const getTimeAndDate = () => {
      const d = new Date()
      const dateOptions = {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      }

      const timeOptions = {
        hour: 'numeric',
        minute: 'numeric',
      }

      date.value = new Intl.DateTimeFormat('en-GB', dateOptions).format(d)
      time.value = new Intl.DateTimeFormat('en-GB', timeOptions).format(d)

      setTimeout(() => {
        getTimeAndDate()
      }, 5000)
    }

    getTimeAndDate()

    return {
      date,
      time,
    }
  },
})
</script>
