// src/newtab/Clock.tsx
import { Component, createSignal } from "solid-js";

export const Clock: Component = () => {
    const [time, setTime] = createSignal("");
    const [date, setDate] = createSignal("");

    const update = () => {
        let now = new Date();
        setTime(now.toLocaleTimeString(undefined, { hourCycle: "h24", hour: '2-digit', minute: '2-digit' }));
        setDate(now.toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }));
    }

    update();
    setInterval(() => update(), 5000);

    return (
        <div>
            <h1>
                <time class="time" dateTime={time()}>{time()}</time>
            </h1>
            <p>
                <time class="date" dateTime={date()}>{date()}</time>
            </p>
        </div>
    );
}

// src/components/Clock.svelte
<script>
	import { onMount } from "svelte";

	// -- Members -- \\
	let date;
	let time;

	// -- Initialization -- \\
	onMount(() => {
		update();
	});

	// -- Functions -- \\
	async function update() {
		const d = new Date();
		date = new Intl.DateTimeFormat("en-GB", {
			year: "numeric",
			month: "short",
			day: "numeric",
			weekday: "short",
		}).format(d);

		time = new Intl.DateTimeFormat("en-GB", {
			hour: "numeric",
			minute: "numeric",
		}).format(d);

		setTimeout(() => {
			update();
		}, 5000);
	}
</script>

<article>
	<h1>{time}</h1>
	<p>{date}</p>
</article>
