// src/App.vue
<template>
  <main class="area area-main">
    <wp-clock />
    <wp-projects />
    <wp-links />
  </main>
  <div id="vert-sep" class="bg-dark-lighter h-auto" />
  <aside class="area area-tasks">
    <wp-tasks />
  </aside>
  <aside class="area area-timer">
    <wp-timer />
  </aside>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Clock from './components/Clock.vue'
import Links from './components/Links.vue'
import Projects from './components/Projects.vue'
import Tasks from './components/Tasks.vue'
import Timer from './components/Timer.vue'

export default defineComponent({
  name: 'App',
  components: {
    'wp-clock': Clock,
    'wp-links': Links,
    'wp-projects': Projects,
    'wp-tasks': Tasks,
    'wp-timer': Timer,
  },
})
</script>

<style lang="postcss">
* {
  box-sizing: border-box;
}

#app {
  width: 100vw;
  height: 100vh;
  display: grid;
  grid-template:
    'main sep tasks' 1fr
    'main sep timer' min-content / 2fr min-content 1fr;

  background: radial-gradient(#3c3836 0%, #282828 70%);
  @apply text-light-lighter font-sans gap-16 p-16;
}

.area {
  @apply flex flex-col items-center justify-center flex-grow;
}

.area-main {
  grid-area: main;
}

#vert-sep {
  grid-area: sep;
  width: 1px;
}

.area-tasks {
  grid-area: tasks;
}

.area-timer {
  grid-area: timer;
}
</style>

// src/App.svelte
<script>
  import Clock from './Clock.svelte';
  import Projects from './Projects.svelte';
  import Links from './Links.svelte';
  import Tasks from './Tasks.svelte';
  import Timer from './Timer.svelte';
</script>

<main class="w-2/3 my-auto">
  <Clock />
  <Projects />
  <Links />
</main>
<aside class="flex flex-col justify-between gap-12">
  <Tasks />
  <Timer />
</aside>

<style lang="postcss" global>
  @tailwind base;
  @tailwind components;
  @tailwind utilities;

  body {
    @apply w-screen h-screen overflow-hidden p-16 flex gap-16 text-gray-900;
    background: radial-gradient(#3c3836 0%, #282828 70%);
  }

  aside {
    @apply w-1/3 pl-16 border-l border-gray-300;
  }

  button {
    @apply flex items-center justify-center gap-1 rounded;
  }

  button > svg {
    @apply h-8;
  }

  input {
    @apply block py-1 px-2 bg-gray-200 border border-gray-400 rounded text-base;
  }

  input:focus {
    @apply border-gray-600;
    outline: none;
  }

  textarea {
    resize: none;
    scrollbar-width: none;
    border-radius: 3px;
    padding: 5px;
    @apply bg-gray-200 border border-gray-400;
  }

  [data-popper-placement^='top'] > [data-popper-arrow] {
    bottom:-4px;
  }

  [data-popper-placement^='right'] > [data-popper-arrow] {
    left:-4px;
  }

  [data-popper-placement^='bottom'] > [data-popper-arrow] {
    top:-4px;
  }

  [data-popper-placement^='left'] > [data-popper-arrow] {
    right:-4px;
  }

  [data-popper-arrow],
  [data-popper-arrow]::before {
    position: absolute;
    display: block;
    width: 8px;
    height: 8px;
    z-index: -1;
  }

  [data-popper-arrow]::before {
    content: '';
    transform: rotate(45deg);
  }
</style>
