// src/entries/newtab/components/Clock.tsx
import { Component } from "solid-js";
import { createDateNow } from "@solid-primitives/date";

const Clock: Component = () => {
    // updates every second:
    const [now] = createDateNow(1000);

    return (
        <div class="text-center">
            <h1 class="text-6xl font-bold py-1">{now().toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}</h1>
            <span>{now().toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric'})}</span>
        </div>
    )
}

export default Clock;

// src/Clock.svelte
<script>
  import { onMount } from 'svelte';

  let date = "date";
  let time = "time";

  function update() {
    const d = new Date()
    date = new Intl.DateTimeFormat('en-GB', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }).format(d)

    time = new Intl.DateTimeFormat('en-GB',  {
      hour: 'numeric',
      minute: 'numeric',
    }).format(d)

    setTimeout(() => {
      update()
    }, 5000);
  };

  onMount(() => {
    update();
  });
</script>

<article class="flex flex-col items-center justify-center">
  <h1 class="text-7xl">{time}</h1>
  <p class="text-2xl">{date}</p>
</article>
