// src/components/util/Popup.vue
<template>
  <button
    ref="reference"
    aria-describedby="tooltip"
    v-bind="$attrs"
    @click.stop="show()"
  >
    <slot></slot>
  </button>
  <div
    class="tooltip z-40 rounded-lg bg-light-lighter text-dark-darker shadow-xl"
    ref="popper"
    role="tooltip"
    v-show="showPopper"
    @click.stop=""
  >
    <slot name="tooltip"></slot>
    <div class="arrow" data-popper-arrow></div>
  </div>
</template>

<script>
import { createPopper } from '@popperjs/core'

export default {
  props: {
    placement: { type: String, default: 'top' },
  },
  data() {
    return {
      popperJS: null,
      showPopper: false,
      popperOptions: {
        placement: this.placement,
      },
    }
  },

  methods: {
    show() {
      if (!this.popperJS) {
        this.createPopper()

        this.showPopper = true
        document.addEventListener('click', this.handleDocumentClick)
      }
    },

    hide() {
      this.destroyPopper()
      this.showPopper = false
      document.removeEventListener('click', this.handleDocumentClick)
    },

    createPopper() {
      this.$nextTick(() => {
        if (this.popperJS && this.popperJS.destroy) {
          this.popperJS.destroyPopper()
        }

        this.popperOptions.onCreate = () => {
          this.$emit('created', this)
          this.$nextTick(this.updatePopper)
        }

        this.popperJS = createPopper(
          this.$refs.reference,
          this.$refs.popper,
          this.popperOptions
        )
      })
    },

    destroyPopper() {
      this.showPopper = false

      if (this.popperJS) {
        this.popperJS.destroy()
        this.popperJS = null
      }
    },

    updatePopper() {
      this.popperJS ? this.popperJS.scheduleUpdate() : this.createPopper()
    },

    handleDocumentClick(e) {
      this.$emit('click-away', this)
      this.hide()
    },
  },

  unmounted() {
    this.destroyPopper()
  },
}
</script>

<style scoped>
.arrow,
.arrow::before {
  position: absolute;
  width: 8px;
  height: 8px;
  z-index: -1;
}

.arrow::before {
  content: '';
  transform: rotate(45deg);
  @apply bg-light-lighter;
}

.tooltip[data-popper-placement^='top'] > .arrow {
  bottom: -4px;
}

.tooltip[data-popper-placement^='bottom'] > .arrow {
  top: -4px;
}

.tooltip[data-popper-placement^='left'] > .arrow {
  right: -4px;
}

.tooltip[data-popper-placement^='right'] > .arrow {
  left: -4px;
}
</style>

// src/Popup.svelte
<script>
	import { createPopper } from '@popperjs/core';
	import { onMount } from 'svelte';

	let reference;
	let popup;
	let show = false;

	onMount(() => {
		console.log(reference);
		console.log(popup);
		createPopper(reference, popup, {
			placement: 'top',
		});
	});
</script>

<style>
	.popup {
		position: relative;
	}

	.tooltip {
		position: absolute;	
		background: var(--tone-900);
		color: var(--tone-100);
		padding: var(--space-2);
		border-radius: var(--rounded);
		box-shadow: var(--shadow-lg);
	}

	.arrow,
	.arrow::before {
		position: absolute;
		width: 8px;
		height: 8px;
		z-index: -1;
	}

	.arrow::before {
		content: '';
		transform: rotate(45deg);
		background: var(--tone-900);
	}

	.tooltip[data-popper-placement^='top'] > .arrow {
		bottom: -4px;
	}

	.tooltip[data-popper-placement^='bottom'] > .arrow {
		top: -4px;
	}

	.tooltip[data-popper-placement^='left'] > .arrow {
		right: -4px;
	}

	.tooltip[data-popper-placement^='right'] > .arrow {
		left: -4px;
	}
</style>

<div class="popup">
	<button bind:this={reference} on:click="{() => show = !show}">
		<slot></slot>
	</button>
	<div class="tooltip" bind:this={popup} hidden={!show}>
		<slot name="tooltip"></slot>	
		<div class="arrow" data-popper-arrow></div>
	</div>
</div>
